domain_path: C:\Users\fall4\Documents\Cora-Z7_07S\Vitis\CET_UART_FW\CET_UART_FW\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
