domain_path: C:\Users\fall4\Documents\Cora-Z7_07S\Vitis\CET_UART_FW\CET_UART_FW\export\CET_UART_FW\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
